Repository refind-opensw/refind-web_history, pull requests merged in 2019-09, with the labels that each got.

#2 Dhoon
  server/routes/index.js
Labels: enhancement

#4 Node.js와 파이썬 연동 #2
  server/pyscripts/test.py
  server/routes/index.js
Labels: enhancement

#11 Sain
  .gitignore
  server/pyscripts/url_wordfreq_seeker.py
  server/routes/index.js
Labels: 버그

#16 프론트 UI 완성 및 검색 데이터 구조화 #6 #12
  client/css/main.css
  client/js/commons.js
  client/js/jquery.mousewheel.min.js
  client/js/main.js
  client/main.html
  client/manifest.json
  server/routes/index.js
Labels: 기능 개선, 기능 구현

#18 세로 - 가로 스크롤 바인딩 해제 #17
  client/js/commons.js
Labels: 버그
