Repository refind-opensw/refind-web_history, pull requests merged in 2019-10, with the labels that each got.

#22 파이썬 Tf-idf 및 LDA 활용하여 주제 탐색 기능 및 각종 에러 예외처리 구현#13 #14 #21
  server/pyscripts/url_wordfreq_seeker.py
Labels: 기능 개선, 기능 구현, 버그

#26 변경된 카테고리 적용 및 UI 변경
  client/css/main.css
  client/img/ic_cat_animal.png
  client/img/ic_cat_education.png
  client/img/ic_cat_fashion.png
  client/img/ic_cat_finance.png
  client/img/ic_cat_food.png
  client/img/ic_cat_geography.png
  client/img/ic_cat_house.png
  client/js/commons.js
  server/pyscripts/categorize.py
  server/pyscripts/url_wordfreq_seeker.py
  server/routes/index.js
Labels: 기능 개선

#28 categorize.py , urlwordfreq_seeker.py 파일 코드 리팩토링 (#27)
  server/pyscripts/categorize.py
  server/pyscripts/url_wordfreq_seeker.py
Labels: 문서 작업 필요
